project:
  type: website

execute:
  freeze: auto

website:
  title: "Reproducing Quality Decomposition"
  repo-url: https://github.com/sergegoussev/quality_decomposition
  repo-actions: [source]
  repo-branch: main
  bread-crumbs: true
  page-navigation: true
  back-to-top-navigation: true
  search: true
  sidebar:
    style: "docked"
    type: "dark"
    title: "Reproducing Krsinich (2024) Quality Decomposition"
    search: true
    border: true
    contents:
      - href: docs/index.qmd
        text: Overview
      - section: "Data preparation"
        contents:
          - href: notebooks/data_wrangling.ipynb
      - section: "Price indices"
        contents: 
          - href: notebooks/price-indices.qmd



format:
  html:
    theme: 
      dark: cyborg
      light: flatly
    css: docs/styles.css
    toc: true