name: quality-decomposition

channels:
  - conda-forge
  - defaults

dependencies:
  # Python packages
  - python=3.12
  - pandas
  - numpy
  - scikit-learn
  - ipykernel

  # R packages
  - r-base
  - r-tidyverse
  - r-irkernel
  - r-essentials
  - r-arrow
  - r-dplyr
  - r-plotly
  - r-gpindex

  # Other tools
  - mamba
  - pip
